version: "3.8"

volumes:
  stock_data:  # For our SQLite .db file
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT= zookeeper:2181
      - KAFKA_CFG_LISTENERS= PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS= PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"

  producer:
    build:
      context: .
      dockerfile: ./producer/Dockerfile
    container_name: producer
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - TIINGO_API_KEY=${TIINGO_API_KEY}

  consumer:
    build:
      context: .
      dockerfile: ./consumer/Dockerfile
    container_name: consumer
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - stock_data:/data

  webapp:
    build: 
      context: .
      dockerfile: ./webapp/Dockerfile
    container_name: webapp
    depends_on:
      - consumer
    ports:
      - "5000:5000"
    volumes:
      - stock_data:/data
